import { promises as fs } from 'fs';
import path from 'path';
import type { RepoIndexWorkflow } from '../models/repo-index.js';

// ─── Script templates ─────────────────────────────────────────────────────────

/**
 * Generate the content of push.sh for a given worktree session.
 *
 * push.sh reads workflow metadata from HORUS_DATA_PATH/config/repos.json to
 * determine the correct `git push` target. It accepts optional extra args
 * (e.g., --force-with-lease) forwarded to git.
 *
 * Workflow mapping:
 *   owner       → git push origin <branch>
 *   fork        → git push origin <branch>  (origin = the user's fork)
 *   contributor → git push origin <branch>
 *
 * All three types push to `pushTo` (always "origin" by convention). The
 * distinction matters for create-pr.sh, not for the push target itself.
 */
export function buildPushScript(workflow: RepoIndexWorkflow, repoName: string): string {
  const pushTo = workflow.pushTo;
  const displayLabel = workflowDisplayLabel(workflow);

  return `#!/bin/sh
# push.sh — generated by forge_develop for ${repoName}
# Workflow: ${workflow.type} (${displayLabel})
# Generated: ${new Date().toISOString()}
#
# Usage: ./push.sh [extra-git-push-args...]
#   e.g. ./push.sh --force-with-lease
#
# Reads current branch from git and pushes to the correct remote.
# Do not edit this file — regenerated by forge_develop on each session.

set -e

PUSH_REMOTE="${pushTo}"
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

if [ -z "$CURRENT_BRANCH" ] || [ "$CURRENT_BRANCH" = "HEAD" ]; then
  echo "ERROR: Could not determine current branch (detached HEAD?)" >&2
  exit 1
fi

echo "Pushing branch '$CURRENT_BRANCH' to $PUSH_REMOTE (${displayLabel})..."
git push "$PUSH_REMOTE" "$CURRENT_BRANCH" "$@"
echo "Done."
`;
}

/**
 * Generate the content of create-pr.sh for a given worktree session.
 *
 * create-pr.sh constructs the correct `gh pr create` invocation based on
 * workflow type:
 *
 *   owner / contributor → gh pr create --base <prTarget.branch>
 *   fork                → gh pr create --repo <prTarget.repo> --base <prTarget.branch>
 *                                       --head <fork-owner>:<branch>
 *
 * Usage: ./create-pr.sh --title "..." --body "..."
 *        (all args forwarded to gh pr create)
 */
export function buildCreatePrScript(workflow: RepoIndexWorkflow, repoName: string): string {
  const { type, prTarget } = workflow;

  let prCommand: string;

  if (type === 'fork') {
    // For fork workflows we must push to origin (the fork) and target the upstream repo.
    // The head reference must include the fork owner, e.g. "myuser:feature/branch".
    // We derive the fork owner from the fork remote URL.
    prCommand = `
# Fork workflow: PR targets the upstream repo from your fork.
# Derive fork owner from origin remote URL.
FORK_REMOTE_URL="$(git remote get-url origin 2>/dev/null || echo '')"
FORK_OWNER=""
if [ -n "$FORK_REMOTE_URL" ]; then
  # Extract owner from git@github.com:owner/repo.git or https://github.com/owner/repo
  FORK_OWNER="$(echo "$FORK_REMOTE_URL" | sed -E 's|.*[:/]([^/]+)/[^/]+(\\.git)?$|\\1|')"
fi

if [ -z "$FORK_OWNER" ]; then
  echo "WARNING: Could not determine fork owner from origin remote URL." >&2
  echo "         You may need to pass --head manually." >&2
  exec gh pr create --repo "${prTarget.repo}" --base "${prTarget.branch}" "$@"
fi

CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo "Creating PR: $FORK_OWNER:$CURRENT_BRANCH → ${prTarget.repo}@${prTarget.branch}"
exec gh pr create --repo "${prTarget.repo}" --base "${prTarget.branch}" --head "$FORK_OWNER:$CURRENT_BRANCH" "$@"
`;
  } else {
    // owner or contributor: PR stays in the same repo
    prCommand = `
# ${type === 'owner' ? 'Owner' : 'Contributor'} workflow: PR targets the same repo.
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo "Creating PR: $CURRENT_BRANCH → ${prTarget.repo}@${prTarget.branch}"
exec gh pr create --base "${prTarget.branch}" "$@"
`;
  }

  return `#!/bin/sh
# create-pr.sh — generated by forge_develop for ${repoName}
# Workflow: ${workflow.type} (target: ${prTarget.repo}@${prTarget.branch})
# Generated: ${new Date().toISOString()}
#
# Usage: ./create-pr.sh --title "feat: my change" --body "Description"
#        (additional args forwarded to gh pr create)
#
# Requires: gh (GitHub CLI) installed and authenticated.
# Do not edit this file — regenerated by forge_develop on each session.

set -e
${prCommand}`;
}

// ─── Hook templates ───────────────────────────────────────────────────────────

/**
 * Generate the content of the pre-push git hook.
 *
 * Validates that the push target remote matches workflow.pushTo.
 * If the agent tries to push to the wrong remote (e.g., directly to
 * upstream instead of origin on a fork workflow), the hook rejects it
 * with a clear error message.
 *
 * pre-push receives: <remote-name> <remote-url> on stdin line pairs
 * The remote name is passed as $1 by git.
 */
export function buildPrePushHook(workflow: RepoIndexWorkflow, repoName: string): string {
  const expectedRemote = workflow.pushTo;

  return `#!/bin/sh
# pre-push hook — generated by forge_develop for ${repoName}
# Workflow: ${workflow.type}
# Generated: ${new Date().toISOString()}
#
# Enforces that pushes go to the correct remote ('${expectedRemote}').
# This prevents accidental direct-pushes to upstream on fork workflows.

REMOTE="$1"
EXPECTED_REMOTE="${expectedRemote}"

if [ "$REMOTE" != "$EXPECTED_REMOTE" ]; then
  echo "" >&2
  echo "forge pre-push: REJECTED" >&2
  echo "" >&2
  echo "  You tried to push to: $REMOTE" >&2
  echo "  Workflow '${workflow.type}' requires pushing to: $EXPECTED_REMOTE" >&2
  echo "" >&2
  echo "  Use: git push $EXPECTED_REMOTE <branch>" >&2
  echo "  Or:  .forge/scripts/push.sh" >&2
  echo "" >&2
  exit 1
fi

exit 0
`;
}

/**
 * Generate the content of the commit-msg git hook.
 *
 * If workflow.commitFormat === "conventional", validates that the commit
 * message follows the Conventional Commits spec:
 *   <type>(<scope>): <description>
 *   where type ∈ {feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert}
 *
 * If commitFormat is not set or is not "conventional", the hook is a no-op.
 *
 * The commit message file path is passed as $1 by git.
 */
export function buildCommitMsgHook(workflow: RepoIndexWorkflow, repoName: string): string {
  if (workflow.commitFormat !== 'conventional') {
    // No-op hook — pass through unconditionally
    return `#!/bin/sh
# commit-msg hook — generated by forge_develop for ${repoName}
# Workflow: ${workflow.type} (commitFormat: ${workflow.commitFormat ?? 'none'})
# Generated: ${new Date().toISOString()}
#
# No commit format enforcement configured for this workflow.
exit 0
`;
  }

  return `#!/bin/sh
# commit-msg hook — generated by forge_develop for ${repoName}
# Workflow: ${workflow.type} (commitFormat: conventional)
# Generated: ${new Date().toISOString()}
#
# Enforces Conventional Commits format:
#   <type>(<scope>): <description>
#   <type>: <description>
#
# Valid types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
#
# Reference: https://www.conventionalcommits.org/

COMMIT_MSG_FILE="$1"
COMMIT_MSG="$(head -1 "$COMMIT_MSG_FILE")"

# Skip merge commits and fixups
case "$COMMIT_MSG" in
  Merge*|Revert*|fixup!*|squash!*) exit 0 ;;
esac

# Validate conventional commit format
# Pattern: type(scope): description  OR  type!: description (breaking change)
if ! echo "$COMMIT_MSG" | grep -qE '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\\([^)]+\\))?!?: .+'; then
  echo "" >&2
  echo "forge commit-msg: REJECTED" >&2
  echo "" >&2
  echo "  Message: $COMMIT_MSG" >&2
  echo "" >&2
  echo "  Expected Conventional Commits format:" >&2
  echo "    <type>(<scope>): <description>" >&2
  echo "    <type>: <description>" >&2
  echo "" >&2
  echo "  Valid types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert" >&2
  echo "  Examples:" >&2
  echo "    feat(forge): add workflow enforcement hooks" >&2
  echo "    fix: correct push target for fork workflow" >&2
  echo "    chore: update dependencies" >&2
  echo "" >&2
  exit 1
fi

exit 0
`;
}

// ─── Installation ─────────────────────────────────────────────────────────────

/**
 * Human-readable label for a workflow, used in script output messages.
 */
function workflowDisplayLabel(workflow: RepoIndexWorkflow): string {
  if (workflow.type === 'fork') {
    return `fork → ${workflow.prTarget.repo}`;
  }
  if (workflow.type === 'contributor') {
    return `contributor → ${workflow.prTarget.repo}@${workflow.prTarget.branch}`;
  }
  return `owner of ${workflow.prTarget.repo}`;
}

/**
 * Install enforcement scripts and hooks into a worktree session.
 *
 * Scripts go to: <sessionPath>/.forge/scripts/
 *   - push.sh
 *   - create-pr.sh
 *
 * Hooks go to: <worktreeBasePath>/.git/hooks/
 *   - pre-push
 *   - commit-msg
 *
 * `worktreeBasePath` is the base repo (managed clone), whose `.git` is a real
 * directory. In a git worktree, `sessionPath/.git` is a file (not a dir), so
 * hooks must be installed into the base repo's `.git/hooks/` instead.
 *
 * All scripts/hooks are chmod 755 (executable).
 *
 * If workflow is null (repo has no confirmed workflow yet), installs
 * no-op placeholder hooks so git operations don't fail. The scripts
 * still run but print a warning.
 */
export async function installEnforcementHooks(
  sessionPath: string,
  workflow: RepoIndexWorkflow | null,
  repoName: string,
  worktreeBasePath: string,
): Promise<void> {
  const hooksDir = path.join(worktreeBasePath, '.git', 'hooks');
  const scriptsDir = path.join(sessionPath, '.forge', 'scripts');

  await fs.mkdir(hooksDir, { recursive: true });
  await fs.mkdir(scriptsDir, { recursive: true });

  if (!workflow) {
    // No confirmed workflow — install pass-through placeholders
    const placeholder = (name: string) => `#!/bin/sh\n# ${name} — no workflow configured\nexit 0\n`;
    await fs.writeFile(path.join(hooksDir, 'pre-push'), placeholder('pre-push'), { mode: 0o755 });
    await fs.writeFile(path.join(hooksDir, 'commit-msg'), placeholder('commit-msg'), { mode: 0o755 });
    await fs.writeFile(path.join(scriptsDir, 'push.sh'), placeholder('push.sh'), { mode: 0o755 });
    await fs.writeFile(path.join(scriptsDir, 'create-pr.sh'), placeholder('create-pr.sh'), { mode: 0o755 });
    return;
  }

  // Hooks
  const prePushContent = buildPrePushHook(workflow, repoName);
  const commitMsgContent = buildCommitMsgHook(workflow, repoName);
  await fs.writeFile(path.join(hooksDir, 'pre-push'), prePushContent, { mode: 0o755 });
  await fs.writeFile(path.join(hooksDir, 'commit-msg'), commitMsgContent, { mode: 0o755 });

  // Scripts
  const pushScriptContent = buildPushScript(workflow, repoName);
  const createPrScriptContent = buildCreatePrScript(workflow, repoName);
  await fs.writeFile(path.join(scriptsDir, 'push.sh'), pushScriptContent, { mode: 0o755 });
  await fs.writeFile(path.join(scriptsDir, 'create-pr.sh'), createPrScriptContent, { mode: 0o755 });
}
