apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: horus-system

commonLabels:
  app.kubernetes.io/part-of: horus-control-plane
  app.kubernetes.io/component: backup

resources:
  - backup.yaml
