#!/bin/sh
# commit.sh — generated by forge_develop for Horus
# Generated: 2026-04-03T06:37:41.830Z
#
# Usage: ./commit.sh <type> <scope> <description>
#   e.g. ./commit.sh feat forge "add a new feature"
#        ./commit.sh fix  auth  "handle expired token"
#
# Produces a conventional commit: <type>(<scope>): <description>
# Do not edit this file — regenerated by forge_develop on each session.

set -e

TYPE="$1"
SCOPE="$2"
DESCRIPTION="$3"

if [ -z "$TYPE" ] || [ -z "$SCOPE" ] || [ -z "$DESCRIPTION" ]; then
  echo "Usage: $0 <type> <scope> <description>" >&2
  echo "  e.g. $0 feat forge \"add commit.sh to session scripts\"" >&2
  exit 1
fi

COMMIT_MSG="$TYPE($SCOPE): $DESCRIPTION"

echo "Committing: $COMMIT_MSG"
git commit -m "$COMMIT_MSG"
echo "Done."
