#!/bin/sh
# create-pr.sh — generated by forge_develop for Horus
# Workflow: owner (target: Arjunkhera/Horus@master)
# Generated: 2026-04-03T06:37:41.830Z
#
# Usage: ./create-pr.sh --title "feat: my change" --body "Description"
#        (additional args forwarded to gh pr create)
#
# Requires: gh (GitHub CLI) installed and authenticated.
# Do not edit this file — regenerated by forge_develop on each session.

set -e

# Owner workflow: PR targets the same repo.
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo "Creating PR: $CURRENT_BRANCH → Arjunkhera/Horus@master"
exec gh pr create --base "master" "$@"
