#!/bin/sh
# push.sh — generated by forge_develop for Horus
# Workflow: owner (owner of Arjunkhera/Horus)
# Generated: 2026-03-24T17:40:27.023Z
#
# Usage: ./push.sh [extra-git-push-args...]
#   e.g. ./push.sh --force-with-lease
#
# Reads current branch from git and pushes to the correct remote.
# Do not edit this file — regenerated by forge_develop on each session.

set -e

PUSH_REMOTE="origin"
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

if [ -z "$CURRENT_BRANCH" ] || [ "$CURRENT_BRANCH" = "HEAD" ]; then
  echo "ERROR: Could not determine current branch (detached HEAD?)" >&2
  exit 1
fi

echo "Pushing branch '$CURRENT_BRANCH' to $PUSH_REMOTE (owner of Arjunkhera/Horus)..."
git push "$PUSH_REMOTE" "$CURRENT_BRANCH" "$@"
echo "Done."
