/**
 * Fastify type augmentations for anvil-router.
 *
 * Extends FastifyRequest with fields populated by the auth plugin:
 *   - request.principal   — verified Principal (tenant, user, role)
 *   - request.forwardedAuth — raw Authorization header for downstream forwarding
 *
 * Extends FastifyRequest with fields populated by the observability plugin (TA-10):
 *   - request.requestId   — X-Request-Id (read from inbound header or generated UUID)
 *   - request.startTimeMs — epoch ms when onRequest hook ran (for duration calculation)
 */

import type { Principal } from '@horus/auth'

declare module 'fastify' {
  interface FastifyRequest {
    /** Populated by the auth preHandler after successful JWT verification. */
    principal?: Principal
    /**
     * Raw Authorization header value stored for downstream proxy use.
     * Proxy stories TA-5/6/7 read this to forward the token to per-user Anvil instances.
     */
    forwardedAuth?: string

    // ── TA-10: Observability fields ──────────────────────────────────────────

    /**
     * X-Request-Id for this request. Read from the inbound header if present;
     * otherwise a UUID generated by the observability plugin's onRequest hook.
     * Echoed back in the response X-Request-Id header and included in log lines
     * and error envelopes.
     */
    requestId?: string

    /**
     * Unix epoch milliseconds captured in the onRequest hook.
     * Used by the onSend hook to compute request duration for logging and metrics.
     */
    startTimeMs?: number
  }
}
