apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: horus-backup
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/arjunkhera/horus.git
    targetRevision: HEAD
    path: deploy/backup
  destination:
    server: https://kubernetes.default.svc
    namespace: horus-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
