---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forge-registry-secrets
  namespace: horus-system
spec:
  encryptedData:
    FORGE_REGISTRY_S3_ACCESS_KEY_ID: AgBa9uMpc/Jm9vCEp3MqH9tWplfd4+ueTzPxqf20naqYQCFlyh3uSvlL+bCyDaU+JflhPBR2bWhPzyLnO00YiVikt7IKUSYX0HCx/HPUae2EFVq1/QG1bRovz1qgKIaLU3I/tk6IYtVbOGln2iHjpppAFaFXDIWGj8IZtGXKop0edlgaxmspuvT//oAuoa+onvh/q8Lio8nw9gh4pWqZ3DpBlvusy3PLTGQX/uxNqcGu/MVpysbc+YL2PfkM4M81afoPuZZyCBdbovZRRO/bqw8yTRGlLmtSRyPDFSBQ+fi+0ivhaS36LgJTVKzWEAgU5ev/PsAvbVeWLN3OQbiWaU0SFsJKQ50khqrFg9yOa206pSFfA45fgQbrzwyWiNS6oj0jwAElZQJBWhyhs5z4rQc3zXBrkMqwv+/ruIDmuaNyEwNjvGgHBJv8oX9OicAmeJPpjQTi8pyh3k/rtsNz9bEb7GzeZioQUaPDfc+3nM4QnuTrRLG53dCw52hEV1e4qjh8m+KCATIdDEVPFbro5cz20+rSQmDzCP9vW/JukcmZNc6ZJLoRGG8Ee4ubRq2eBOVzPGpLjreUfUjInPs1ZbFOenQCipUSbCgXRfJELthf05Z0R1NPVnoh9K7NS3FQBuum4lGs7G/f/UiOtvVAH3vW0X10cO+nTWztF6zxdjLJzmXNR7ZJjP6KfY3pxiJ8KABIwm+50GzNUEU70NVb6D5uB1fIKA==
    FORGE_REGISTRY_S3_SECRET_ACCESS_KEY: AgArCq140Qv6YFkgi4PQvO1+PKdKHtqgQsMt3up/bnUibA+NzHfVo8vGzFgHtQjsj/DQeEusRqNXkKV71LjxwXoNWCTHze0jYBFHVZGaL3O+R00bXzg/Iz2plqEWSkUqV9pl2uclrpd+jin9fcaaytafDOXUSxPREOwH0P3BGhvK2fvBSHs+d7NbRChse6mXK2ZbMOsjv7T9nQfLm9mh5gyvUjqE/tFYDNgptpQg79V9/vaE+fpbGHbjcJd+8jEhwv8IvCA3jLWu+UNAGB/4mOTf3LYzoTy66n0H7en6pNveg1azwtKWTYM1LdafJbUkxQcf+f+nYbOL08irm9EBL8/Syff5aAjHjlVXFu/HyWxdH7hYSG6tlVIYsEN0BU4splbB4nWagv4lt5VUEZVTLFf+P1XypxYtoyeeO1sYDQ42lFlq1QPCuYuDRL7uZARwGmPWsVyo843VKTCIzUautiU5uP/8ju+rxbTZejYr/BfQ6eK2OP50lckSUN3cUPA4I6HTZmsL4zoeiz+OZaQOvRL7K4CQgEzt3Q+jJaNosLA7Ala7jOTQ6QRe4ZvuVb70zO/V4gIvOS4DIq6ijdq/6BBQ97STZGgbAZSQJmszNuErqhIVMlm0kykrUvOMxaSboa+HY8LavngBLJKULeAtrj4ogYv/vFKN2SkCrVZKcblKVzfI1FzGcBYkf/rFiaSSKxQvr8f9X6CNvE7tXutOsGGPMvZd/eQM2plDo3nRbu25qCrwq/ugQPl5
  template:
    metadata:
      creationTimestamp: null
      name: forge-registry-secrets
      namespace: horus-system
