---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: horus-system
spec:
  encryptedData:
    password: AgCTMWQi4uhfFkukvWdWJgk6axeKizSuROWccuSq9i/Tp4FNgIKFdsavBnhmRrTkDSVsOzuIHr4QZFRhMg9g+Y+wug/XOhx2oJBWmL/w9Rbcqh4xLeZ8fSouYVdD+hraucJeYc4+BNyxQ3d7ymn01fxlnbIGCD7TkvQI6fybj20Vey7tXGXgL6+lzuAmu5W+qDRChyxroqqZZE8WGTQy1xhN07qNawDSIWQAJ0pOBjbhDeWQCc8YaJAUhEZUMSpuT7vfi7lBYIuHVE7BUNsySzNqkLCxPaIVzQgyoZcIkOShskIJFlI/YM6n7Vr6F8RauooHd+VgJeh/6oKedHQH7RlMogzdWHzrmkSTumkaDgJf7lTsCq+k82Az6NfDxO+/OCDivbktVTYDPhHjPNvEikryqLAKPJUTcB9/PVkipZ8u4FRTvkqvk1/1eTyRyKoBIHoH55t6EHk4WKAqwYUu3AFmE7BQQcVbBZTzpZElLsf1NLldLroKxIX/VGMNONITdKNCoWaS/0TCuLjJPS/QWRHRn9dLkdEj/0bk2aOCEKyOgk2JjVF8zakVMnK0petNqV+Eci+dggpsEu9z/4YCLhNRibcb5bZjPsupbgO9G0IiKCmq52JGGc3BbFhz0i1DcIQkE6uUvDVEDeT4dyp7Y2MnanWY0xeX1BJ+Janksk6DiUPEjQWmNyYvaEMoFP/l2sP/jic0dldtdZqd6OaoSVpCzfY01uK3Xu9pAbatiJ7U+Q==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: horus-system
