---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: horus-principal-pub
  namespace: horus-system
spec:
  encryptedData:
    pub.jwk: AgBwce5bt46KMIjv7dMheVWMewO0i9JLBg0D2AyfJIfqj0yzyqRtx6jxvqKUYHij8kW06THYTpat41rrEu5yBjfH77wL5T/JUtkbiMMzGXGjCTYXW0sdPvoXel7gzNHSQTgkjke7SgxmEADnLLdOVRF256Maa/iVqNxE9wYP5Ir8lEyjVrXsu39mFcyZOULkgiJr/h3NXQ1SnbdvH5cI84lPqkcSZkv3AXStYRg772bdbheNAvyv3hoNRyuhi+Hv6xHJv7cgcuwiD19laatFhWqd8MFEs+m8OK7TlGG9at83XODVYb1lSSgdW6du+mLHnB9IsxhRUuvX9agB1K58cCgfFUobFhuJgnpdeUqO9nWhZ295jdVLHzpm6iFEbyad3xodrEe9lBY8TOXtBcCkcemlbZoAGNeejxrZXSwOACoKlwjR9vAf+OEk5eAaKcib76cSCOaSTdHtuQGpX4+q+tXFA3DstUssM0DpjXitSKIoDtQxYQN15+/RirGa4SpBP79nbCDSEpovEAxlxMx7ywKItjDwPQs0+L0A0gYVTv8yOinXrHiARUMgTWt6q8C1tp9udrUe6P0XiWryadB1LbyIL7wTwpGtt5FcwNNg7aumUwD4sGJMODv98L83FdTQQCsLhe/GVWej2t3Pc6J5fZCyMdNYABIiiHSdySFToP3wFDlX5brTfrRfxbCZAwHW2yGYrUdhcREVKW0B1kHJKY0JpOVUYc9tLhK0RNFPywIvVDsCWvhtqOdiu0lISKDxrlh9oW0Hanirw46hmy4t4UVox2Nc4RHuP4THZwKB/VXqE/MDopecWQOtGf5LxisK2L+LlbEvFkCezKpEM2c2R63AJ4IWlXXOdFz3yAyKutY=
  template:
    metadata:
      creationTimestamp: null
      name: horus-principal-pub
      namespace: horus-system
